# Generated by Django 3.1.7 on 2023-11-21 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulclass',
            options={'ordering': ('created_at',), 'verbose_name': 'Modul', 'verbose_name_plural': 'Moduls'},
        ),
    ]
