# Generated by Django 3.1.7 on 2023-11-21 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20231121_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoapp',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='video.comment'),
        ),
    ]
