# Generated by Django 4.2.7 on 2023-11-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0005_alter_comment_id_alter_modulclass_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videoapp",
            name="comment",
        ),
        migrations.AddField(
            model_name="videoapp",
            name="comment",
            field=models.ManyToManyField(blank=True, to="video.comment"),
        ),
    ]
